package Javadoc;
// we have to write javadoc comment just above thr class and method with tags
/**
 * Javadoc is the used for generating documentation
* @author Harsh Yadav
* @version 0.1.0
* @since 2025
* @see <a href="https://github.com">docs</a>
*/
public class Javadoc {

    /**
     * method1 is used for do something
     * @params name give it name
     * @return name itself
     * @throws Exception if i is 0
     * @deprecated This method is depreceted
     * */
    public String method1(String name) throws Exception{
        System.out.println("Method1 for doing something..");
        return name;
    }

    /**
     * main is used for starting execution
     * @params args These arguments is used to supplied in command line
     */
    public static void main(String[] args) {
        System.out.println("This is java documentation generated by javadoc.");
    }
}
